server:
  port: 9411

# logback log file
logback_path: /Users/maduar/demo/log/zipkin

zipkin:
  service:
    name: zipkin
  storage:
    type: mysql

spring:
  rabbitmq:
    host: 150.109.49.131
    port: 5672
    username: guest
    password: rabbitMaduar310
    queue: zipkin
  datasource:
    url: jdbc:mysql://localhost:3306/zipkin?autoReconnect=true
    username: root
    password: maduarMysql
    driverClassName: com.mysql.jdbc.Driver
  sleuth:
    enabled: false
