server:
  port: 9411

# logback log file
logback_path: /Users/maduar/demo/log/zipkin

zipkin:
  service:
    name: zipkin
  storage:
    type: mysql

spring:
  application:
    name: zipkin
  rabbitmq:
    host: 150.109.49.131
    port: 5672
    username: guest
    password: rabbitMaduar310
    queue: zipkin
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://150.109.49.131:3306/zipkin?autoReconnect=true
    username: root
    password: maduarMysql
    driverClassName: com.mysql.jdbc.Driver
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false
