server:
  port: 8761
spring:
  application:
    name: eureka_server
  boot:
    admin:
      url: "http://localhost:12300"

security:
  basic:
    enabled: true
  user:
    name: maduar  # 用户名
    password: maduartest   # 用户密码

eureka:
  server:
    enable-self-preservation: false
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
          enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8861/eureka/
