server:
  port: 8761
spring:
  application:
    name: eureka_server
  boot:
    admin:
      url: http://${spring.cloud.client.ipAddress}:12300

info:
  desciption: eureka_server
  component: Web Server

management:
  security:
    enabled: false
