server:
  port: 12300

spring:
  application:
    name: springcloud_admin

info:
  desciption: springcloud_admin
  component: Web Server

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://admin:admin@${spring.cloud.client.ipAddress}:8761/eureka/
