server:
  port: 12306
#  context-path: /${spring.application.name}/api

spring:
  application:
    name: springconfig
  profiles:
    active: dev
#  boot:
#    admin:
#      url:  http://localhost:12300
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://github.com/maduar/springcloud_parent.git #配置git仓库地址
          searchPaths: springcloudconfigfolder #配置仓库路径
      label: master #配置仓库的分
  rabbitmq:
    host: 150.109.49.131
    port: 5672
    username: guest
    password: rabbitMaduar310

params: cococ

info:
  desciption: springcloud_config
  component: Web Server
#  version: @project.version@

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    leaseRenewalIntervalInSeconds: 60  #心跳间隔时间1s (for Dev)
    leaseExpirationDurationInSeconds: 90  #连续2s未响应时将服务注销 (for Dev)
  client:
    serviceUrl:
      defaultZone: http://discoveryActuator:discoveryActuatorPwd@127.0.0.1:8761/eureka/
