spring:
  application:
    name: springcloud-client
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 12307
#  context-path: /${spring.application.name}/api

params: xxxdev00xx22


management:
  security:
    enabled: false
