spring:
  application:
    name: springcloud-client

info:
  desciption: springcloud_client
  component: Web Server
  version: @project.version@

params: xxxclient

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@${spring.cloud.client.ipAddress}:8761/eureka/
