spring:
  application:
    name: springcloud-client

server:
  port: 12309
#  context-path: /${spring.application.name}/api

params: xxxdev00xx22

management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh
eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryActuator:discoveryActuatorPwd@127.0.0.1:8761/eureka/
